"use client";
/* eslint-disable react-hooks/set-state-in-effect */

import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowLeft, ChevronDown, DoorOpen, Flame, Gem, Heart, RotateCcw, ShieldAlert, Sparkles, Zap } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { VAULT_ARTIFACTS, VAULT_CUSTOM_SET_KEY, VAULT_QUESTIONS, type VaultArtifact, type VaultCustomSet, type VaultQuestion } from "@/lib/vaultGame";

type Phase = "home" | "room" | "repair" | "camp" | "relic" | "shrine" | "lost" | "extracted";
type Modifier = "echo" | "fortune" | "lantern" | null;
type Save = { shards: number; bestDepth: number; artifacts: string[]; mastered: string[]; conceptWins?: Record<string, number> };
const EMPTY: Save = { shards: 0, bestDepth: 0, artifacts: [], mastered: [] };

export default function VaultGame() {
  const reduceMotion = useReducedMotion();
  const [phase, setPhase] = useState<Phase>("home"), [save, setSave] = useState<Save>(EMPTY), [ready, setReady] = useState(false);
  const [deck, setDeck] = useState("Mixed Descent"), [customSet, setCustomSet] = useState<VaultCustomSet | null>(null);
  const [depth, setDepth] = useState(1), [light, setLight] = useState(3), [shards, setShards] = useState(0), [combo, setCombo] = useState(0);
  const [picked, setPicked] = useState<number | null>(null), [repairPicked, setRepairPicked] = useState<number | null>(null), [relic, setRelic] = useState<VaultArtifact | null>(null);
  const [carried, setCarried] = useState<string[]>([]), [modifier, setModifier] = useState<Modifier>(null), [eliminated, setEliminated] = useState<number | null>(null), [runWins, setRunWins] = useState<Record<string, number>>({});

  useEffect(() => {
    try {
      const stored = localStorage.getItem("sinon-vault-save-v1"); if (stored) setSave(JSON.parse(stored) as Save);
      const local = localStorage.getItem(VAULT_CUSTOM_SET_KEY); if (local) { const parsed = JSON.parse(local) as VaultCustomSet; if (parsed.questions?.length >= 3) setCustomSet(parsed); }
      const id = new URLSearchParams(window.location.search).get("set");
      if (id === "custom" && local) setDeck((JSON.parse(local) as VaultCustomSet).title);
      if (id && id !== "custom") fetch(`/api/vault/sets/${encodeURIComponent(id)}`).then(r => r.ok ? r.json() : Promise.reject()).then((data: { vaultSet: VaultCustomSet }) => { if (data.vaultSet.questions.length >= 3) { setCustomSet(data.vaultSet); setDeck(data.vaultSet.title); } }).catch(() => undefined);
    } catch { /* Progress is optional. */ }
    setReady(true);
  }, []);

  const pool = useMemo(() => customSet && deck === customSet.title ? customSet.questions : deck === "Mixed Descent" ? VAULT_QUESTIONS : VAULT_QUESTIONS.filter(q => q.subject === deck), [customSet, deck]);
  const question = pool[(depth - 1) % pool.length];
  const order = useMemo(() => [0, 1, 2, 3].map(i => (i + depth * 3 + question.id.length) % 4), [depth, question.id]);
  const persist = (next: Save) => { setSave(next); try { localStorage.setItem("sinon-vault-save-v1", JSON.stringify(next)); } catch { /* Optional. */ } };
  const start = () => { setDepth(1); setLight(3); setShards(0); setCombo(0); setPicked(null); setRepairPicked(null); setRelic(null); setCarried([]); setModifier(null); setEliminated(null); setRunWins({}); setPhase("room"); };
  const answer = (index: number) => {
    if (picked !== null || index === eliminated) return;
    setPicked(index);
    if (index !== question.answer) { setCombo(0); setLight(v => Math.max(0, v - (modifier === "fortune" ? 2 : 1))); window.setTimeout(() => setPhase("repair"), 550); return; }
    const nextCombo = combo + 1; setCombo(nextCombo); setShards(v => v + Math.round((20 + depth * 5 + combo * 3) * (modifier === "fortune" ? 1.5 : 1))); setRunWins(v => ({ ...v, [question.concept]: (v[question.concept] ?? 0) + 1 }));
    window.setTimeout(() => { if (depth % 2 === 0) { const options = VAULT_ARTIFACTS.filter(a => !carried.includes(a.id)); const found = options[(depth + combo) % options.length] ?? VAULT_ARTIFACTS[0]; setRelic(found); setCarried(v => [...v, found.id]); setPhase("relic"); } else setPhase("camp"); }, 600);
  };
  const repair = (index: number) => { if (repairPicked !== null) return; setRepairPicked(index); if (index === question.repairAnswer) setShards(v => v + 10); window.setTimeout(() => { setRepairPicked(null); setPhase(light <= 0 ? "lost" : "camp"); }, 550); };
  const descend = () => { if (depth >= 8) return extract(); setDepth(v => v + 1); setPicked(null); setEliminated(null); setPhase((depth === 3 || depth === 6) ? "shrine" : "room"); };
  const extract = () => { const wins = Object.entries(runWins).reduce((all, [concept, value]) => ({ ...all, [concept]: (all[concept] ?? 0) + value }), { ...(save.conceptWins ?? {}) }); persist({ shards: save.shards + shards, bestDepth: Math.max(save.bestDepth, depth), artifacts: [...new Set([...save.artifacts, ...carried])], mastered: [...new Set([...save.mastered, ...Object.keys(runWins)])], conceptWins: wins }); setPhase("extracted"); };
  if (!ready) return <main className="min-h-screen bg-[#07100f]" />;
  const activeQuestion = phase === "room" && question;
  return <main className="min-h-screen overflow-hidden bg-[#050b0b] text-[#f5edda] selection:bg-cyan-300 selection:text-black">
    <VaultAtmosphere depth={phase === "home" ? 0 : depth}/>
    <header className="relative z-30 flex h-16 items-center justify-between border-b border-white/10 bg-[#050b0b]/80 px-5 backdrop-blur-xl"><Link href="/game-shows" className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.2em] text-[#d5bd7d]"><ArrowLeft size={14}/> Exit vault</Link><p className="font-display text-xl font-black tracking-[.12em]">THE VAULT</p><span className="flex items-center gap-1.5 text-xs font-black text-cyan-200"><Gem size={13}/>{save.shards}</span></header>
    <AnimatePresence mode="wait">
      {phase === "home" ? <Home key="home" deck={deck} customSet={customSet} save={save} onDeck={setDeck} onStart={start}/> : <motion.section key={phase + depth} initial={{ opacity: 0, scale: reduceMotion ? 1 : .985 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0 }} className="relative z-10 mx-auto min-h-[calc(100vh-64px)] max-w-[1500px] px-4 py-4 md:px-8">
        <Hud depth={depth} light={light} shards={shards} combo={combo} carried={carried}/>
        {activeQuestion && <Room question={question} order={order} picked={picked} eliminated={eliminated} modifier={modifier} onEcho={() => { const bad = order.find(i => i !== question.answer); if (bad !== undefined) setEliminated(bad); }} onAnswer={answer}/>} 
        {phase === "repair" && <Repair question={question} picked={repairPicked} onPick={repair}/>} 
        {phase === "camp" && <Camp depth={depth} light={light} shards={shards} onDescend={descend} onExtract={extract}/>} 
        {phase === "relic" && relic && <Relic artifact={relic} onContinue={() => setPhase("camp")}/>} 
        {phase === "shrine" && <Shrine active={modifier} onChoose={(next) => { setModifier(next); if (next === "lantern") setLight(v => Math.min(4, v + 1)); setPhase("room"); }}/>} 
        {phase === "lost" && <End lost shards={Math.floor(shards / 2)} onAgain={start} onHome={() => setPhase("home")}/>} 
        {phase === "extracted" && <End shards={shards} onAgain={start} onHome={() => setPhase("home")}/>} 
      </motion.section>}
    </AnimatePresence>
  </main>;
}

function VaultAtmosphere({ depth }: { depth: number }) { return <div className="pointer-events-none fixed inset-0 bg-[#050b0b]"><div className="absolute inset-0 bg-[radial-gradient(ellipse_at_50%_-20%,rgba(34,157,153,.22),transparent_52%),radial-gradient(ellipse_at_95%_90%,rgba(224,145,57,.13),transparent_35%)]"/><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(197,223,202,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(197,223,202,.025)_1px,transparent_1px)] [background-size:48px_48px]"/><div className="absolute inset-x-0 bottom-0 h-1/2 bg-[linear-gradient(0deg,rgba(0,0,0,.7),transparent)]"/><p className="absolute bottom-5 left-1/2 -translate-x-1/2 text-[9px] font-bold uppercase tracking-[.5em] text-white/15">Sublevel {String(depth).padStart(2, "0")}</p></div>; }
function Home({ deck, customSet, save, onDeck, onStart }: { deck: string; customSet: VaultCustomSet | null; save: Save; onDeck: (v: string) => void; onStart: () => void }) { return <section className="relative z-10 min-h-[calc(100vh-64px)] bg-[linear-gradient(90deg,rgba(5,11,11,.98)_0%,rgba(5,11,11,.82)_35%,rgba(5,11,11,.18)_75%,rgba(5,11,11,.75)_100%),url('/images/vault/vault-gate-hero.png')] bg-cover bg-[center_right] bg-no-repeat px-6 py-14 md:px-14"><div className="max-w-2xl"><p className="flex items-center gap-3 text-[10px] font-black uppercase tracking-[.35em] text-cyan-200"><span className="h-px w-12 bg-cyan-200"/> Curator signal acquired</p><h1 className="mt-7 font-display text-7xl font-black leading-[.76] tracking-[-.06em] md:text-9xl">THE VAULT<br/><span className="text-[#d5ac5f]">IS HUNGRY.</span></h1><p className="mt-9 max-w-md text-base leading-7 text-[#d6cdb8]">A rapid-fire relic run built for any subject. Pick a gate, protect your lantern, build a combo, and get out richer than you entered.</p><div className="mt-9 flex flex-wrap items-end gap-3"><label className="text-[9px] font-black uppercase tracking-[.18em] text-[#b4aa91]">Loadout<select value={deck} onChange={e => onDeck(e.target.value)} className="mt-2 block min-w-56 border border-[#d5bd7d]/35 bg-[#0b1716] px-4 py-3 text-sm font-bold normal-case tracking-normal text-white outline-none"><option>Mixed Descent</option><option>World History</option><option>Biology</option><option>Algebra</option>{customSet && <option>{customSet.title}</option>}</select></label><button onClick={onStart} className="group flex items-center gap-3 bg-[#e0bd70] px-7 py-3.5 text-xs font-black uppercase tracking-[.2em] text-[#081311] shadow-[0_0_45px_rgba(224,189,112,.3)] transition hover:scale-[1.03]">Enter the breach <ChevronDown size={16} className="transition group-hover:translate-y-1"/></button></div><div className="mt-12 flex gap-7 text-[10px] font-black uppercase tracking-[.16em] text-white/45"><span><b className="mr-2 text-cyan-200">{save.bestDepth || 0}</b> deepest run</span><span><b className="mr-2 text-[#d5ac5f]">{save.artifacts.length}</b> relics held</span><Link href="/vault/build" className="text-cyan-100 underline decoration-cyan-400/40 underline-offset-4">Forge a set</Link></div></div></section>; }
function Hud({ depth, light, shards, combo, carried }: { depth: number; light: number; shards: number; combo: number; carried: string[] }) { return <div className="mx-auto flex max-w-6xl items-center justify-between border-b border-white/10 pb-3 text-[10px] font-black uppercase tracking-[.16em]"><span className="text-cyan-200">Run // {String(depth).padStart(2, "0")}</span><div className="flex gap-5 text-[#d9cba9]"><span className="flex items-center gap-1"><Heart size={13} className={light === 1 ? "text-red-300" : "text-amber-200"}/>{light} light</span><span className="flex items-center gap-1 text-cyan-200"><Gem size={13}/>{shards}</span><span className="flex items-center gap-1 text-orange-200"><Flame size={13}/>{combo} combo</span><span className="hidden sm:inline">{carried.length} relics</span></div></div>; }
function Room({ question, order, picked, eliminated, modifier, onEcho, onAnswer }: { question: VaultQuestion; order: number[]; picked: number | null; eliminated: number | null; modifier: Modifier; onEcho: () => void; onAnswer: (v: number) => void }) { const positions = ["left-[5%] top-[38%]", "right-[5%] top-[38%]", "left-[16%] bottom-[4%]", "right-[16%] bottom-[4%]"]; return <div className="relative mx-auto mt-4 h-[calc(100vh-150px)] min-h-[560px] max-w-6xl overflow-hidden border border-cyan-100/10 bg-[radial-gradient(ellipse_at_50%_58%,rgba(29,105,100,.26),transparent_34%),linear-gradient(125deg,#071211,#0a1715_48%,#081110)]"><div className="absolute left-1/2 top-[30%] h-48 w-48 -translate-x-1/2 rounded-full border border-cyan-200/30 bg-cyan-300/10 shadow-[0_0_100px_rgba(71,222,211,.18)]"/><div className="absolute left-1/2 top-[35%] -translate-x-1/2 text-center"><Zap className="mx-auto text-cyan-200"/><p className="mt-3 text-[9px] font-black uppercase tracking-[.3em] text-cyan-200">Objective // {question.subject}</p><h2 className="mt-3 max-w-xl font-display text-2xl font-black leading-tight text-[#f5ecd8] md:text-3xl">{question.prompt}</h2>{modifier === "echo" && eliminated === null && <button onClick={onEcho} className="mt-3 border border-cyan-300/30 bg-cyan-300/10 px-3 py-1.5 text-[9px] font-black uppercase tracking-wider text-cyan-100">Pulse scan · erase false gate</button>}</div><div className="absolute left-[8%] top-0 h-full w-px bg-gradient-to-b from-transparent via-cyan-300/20 to-transparent"/><div className="absolute right-[8%] top-0 h-full w-px bg-gradient-to-b from-transparent via-amber-300/20 to-transparent"/>{order.map((choice, i) => { const isRight = choice === question.answer, isPicked = picked === choice, dead = eliminated === choice; return <button key={choice} disabled={picked !== null || dead} onClick={() => onAnswer(choice)} className={`absolute ${positions[i]} w-[40%] max-w-[360px] border p-4 text-left transition md:w-[30%] ${dead ? "border-white/5 bg-black/30 opacity-15" : isPicked && isRight ? "border-emerald-300 bg-emerald-300/20 shadow-[0_0_40px_rgba(110,231,183,.3)]" : isPicked ? "border-red-300 bg-red-300/15" : "border-[#c9b37a]/30 bg-[#0a1513]/85 hover:-translate-y-1 hover:border-cyan-200 hover:bg-[#102421]"}`}><span className="flex items-center justify-between text-[9px] font-black uppercase tracking-[.18em] text-[#d3b875]"><span>Gate {String.fromCharCode(65 + i)}</span><DoorOpen size={16}/></span><span className="mt-3 block text-sm font-semibold leading-5 text-[#f4eddf]">{dead ? "Rejected signal" : question.choices[choice]}</span>{isPicked && <span className={`mt-3 block text-[9px] font-black uppercase tracking-[.15em] ${isRight ? "text-emerald-200" : "text-red-200"}`}>{isRight ? "Gate opens" : "System fracture"}</span>}</button>; })}</div>; }
function Repair({ question, picked, onPick }: { question: VaultQuestion; picked: number | null; onPick: (v: number) => void }) { return <div className="mx-auto mt-4 flex min-h-[calc(100vh-170px)] max-w-5xl items-center justify-center border border-fuchsia-300/15 bg-[repeating-linear-gradient(0deg,transparent,transparent_5px,rgba(236,72,153,.05)_6px)] px-5"><div className="max-w-2xl text-center"><ShieldAlert className="mx-auto h-12 w-12 text-fuchsia-200"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.3em] text-fuchsia-200">Glitch encounter · stabilize the run</p><h2 className="mt-4 font-display text-3xl font-black">{question.repairPrompt}</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-6 text-fuchsia-100/65">{question.misconception}</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{question.repairChoices.map((choice, i) => <button key={choice} disabled={picked !== null} onClick={() => onPick(i)} className={`border px-6 py-7 text-lg font-bold transition ${picked === i ? i === question.repairAnswer ? "border-emerald-300 bg-emerald-300/15" : "border-red-300 bg-red-300/10" : "border-fuchsia-300/30 bg-[#160e1a] hover:-translate-y-1 hover:border-fuchsia-200"}`}>{choice}</button>)}</div></div></div>; }
function Camp({ depth, light, shards, onDescend, onExtract }: { depth: number; light: number; shards: number; onDescend: () => void; onExtract: () => void }) { return <div className="mx-auto mt-4 flex min-h-[calc(100vh-170px)] max-w-5xl items-center justify-center border-x border-white/10 text-center"><div><p className="text-[10px] font-black uppercase tracking-[.35em] text-cyan-200">Checkpoint // floor {depth}</p><h2 className="mt-4 font-display text-6xl font-black">Keep the run alive?</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-white/50">You have {light} lantern light and {shards} unbanked shards. Your next gate pays more, but darkness takes its cut.</p><div className="mt-9 grid gap-4 sm:grid-cols-2"><button onClick={onExtract} className="border border-[#d6b96f]/35 bg-[#d6b96f]/10 p-6 text-left hover:bg-[#d6b96f]/20"><DoorOpen className="text-[#e7cc83]"/><b className="mt-5 block text-xl">Extract</b><span className="mt-1 block text-xs text-white/50">Bank everything now.</span></button><button onClick={onDescend} className="border border-cyan-300/35 bg-cyan-300/10 p-6 text-left hover:bg-cyan-300/20"><ChevronDown className="text-cyan-200"/><b className="mt-5 block text-xl">{depth >= 8 ? "Open final seal" : "Dive deeper"}</b><span className="mt-1 block text-xs text-white/50">Push the combo. Find more relics.</span></button></div></div></div>; }
function Relic({ artifact, onContinue }: { artifact: VaultArtifact; onContinue: () => void }) { return <div className="mx-auto mt-4 flex min-h-[calc(100vh-170px)] max-w-5xl items-center justify-center border border-[#d6b96f]/20 text-center"><div><p className="text-[10px] font-black uppercase tracking-[.3em] text-[#e1c475]">Relic acquired</p><motion.div initial={{ scale: .4, rotate: -20 }} animate={{ scale: 1, rotate: 0 }} className="mx-auto mt-7 flex h-52 w-52 items-center justify-center border border-[#e8cd87]/45 bg-[#d6b96f]/10 font-display text-8xl text-[#f6df9d] shadow-[0_0_100px_rgba(224,189,112,.22)]">{artifact.glyph}</motion.div><h2 className="mt-6 font-display text-5xl font-black">{artifact.name}</h2><p className="mx-auto mt-3 max-w-md text-sm italic text-white/55">“{artifact.lore}”</p><button onClick={onContinue} className="mt-8 bg-[#e0bd70] px-6 py-3 text-xs font-black uppercase tracking-[.18em] text-[#07100f]">Stow relic</button></div></div>; }
function Shrine({ active, onChoose }: { active: Modifier; onChoose: (v: Exclude<Modifier, null>) => void }) { const options = [["echo", "Echo Lens", "Erase one false gate in every chamber."], ["fortune", "Fortune Oath", "Earn 50% more. Mistakes cost two light."], ["lantern", "Deep Lantern", "Gain a fourth lantern light."]] as const; return <div className="mx-auto mt-4 flex min-h-[calc(100vh-170px)] max-w-6xl items-center justify-center text-center"><div><p className="text-[10px] font-black uppercase tracking-[.35em] text-violet-200">Between-world shrine</p><h2 className="mt-4 font-display text-5xl font-black">Choose your curse.</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{options.map(([id, name, text]) => <button key={id} onClick={() => onChoose(id)} className={`w-64 border p-6 text-left transition hover:-translate-y-2 ${active === id ? "border-violet-200 bg-violet-300/15" : "border-white/15 bg-[#0a1514] hover:border-violet-200"}`}><Sparkles className="text-violet-200"/><b className="mt-7 block text-xl">{name}</b><span className="mt-2 block text-xs leading-5 text-white/55">{text}</span></button>)}</div></div></div>; }
function End({ lost, shards, onAgain, onHome }: { lost?: boolean; shards: number; onAgain: () => void; onHome: () => void }) { return <div className="mx-auto mt-4 flex min-h-[calc(100vh-170px)] max-w-5xl items-center justify-center text-center"><div><div className={`mx-auto flex h-24 w-24 items-center justify-center rounded-full border ${lost ? "border-red-300/30 bg-red-300/10" : "border-cyan-300/30 bg-cyan-300/10"}`}>{lost ? <Flame size={38} className="text-red-200"/> : <Gem size={38} className="text-cyan-200"/>}</div><p className="mt-7 text-[10px] font-black uppercase tracking-[.3em] text-[#d5bd7d]">{lost ? "Lantern extinguished" : "Relics secured"}</p><h2 className="mt-3 font-display text-6xl font-black">{lost ? "The Vault takes its due." : "You got out."}</h2><p className="mt-4 text-sm text-white/55">{shards} shards recovered.</p><div className="mt-8 flex justify-center gap-3"><button onClick={onHome} className="border border-white/20 px-5 py-3 text-xs font-black uppercase tracking-wider">Home</button><button onClick={onAgain} className="flex items-center gap-2 bg-[#e0bd70] px-5 py-3 text-xs font-black uppercase tracking-wider text-[#07100f]"><RotateCcw size={14}/> Run again</button></div></div></div>; }
